# Ian Schlierf
## Week 10 - 10/27/2020
### Python numpy intro

In [1]:
import numpy as np

In [2]:
np.version

<module 'numpy.version' from 'c:\\Miniconda\\envs\\py37_default\\lib\\site-packages\\numpy\\version.py'>

In [3]:
np.__version__

'1.18.5'

In [4]:
#numpy is a way to manipulate lists
#Written in C++ and Python to make it more efficient

In [5]:
arr = np.array([1,2,3,4,5,6])

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr.type()

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array((1,2,3,4,5,6))

In [10]:
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
#0-D Arrays
arr2 = np.array(50)

In [13]:
arr2

array(50)

In [15]:
#1-D array
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [20]:
#2-D array - matrix

arr4 = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])

print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [21]:
#3-D array
arr5 = np.array([[[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]]])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [22]:
print(arr2.ndim)

0


In [23]:
print(arr3.ndim)

1


In [24]:
print(arr4.ndim)

2


In [25]:
print(arr5.ndim)

3


In [26]:
#array indexing
print(arr3)

[1 2 3 4 5 6]


In [27]:
print(arr3[1])

2


In [28]:
print(arr3[-1])

6


In [29]:
#Access 2-D array
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [31]:
print(arr4[1][0])

11


In [32]:
print(arr4[-1][-1])

66


In [36]:
print(arr4[0][3])

4


In [37]:
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [38]:
print(arr5[-1][-1][-1])

66


In [41]:
print(arr5[1][0][2])

33


In [43]:
marr = np.array([1,2,3,4,5], ndmin=5)

In [45]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [46]:
marr.ndim

5

In [47]:
#slicing np arrays
#[start:end]
#[start:end:step]
#[:end] start is 0
#[start:] end is length of arr


In [48]:
print(arr3)

[1 2 3 4 5 6]


In [49]:
arr3.ndim

1

In [51]:
print(arr3[1:4])
#includes the start index but not the last

[2 3 4]


In [52]:
print(arr3[3:])

[4 5 6]


In [55]:
#Slice elements from the beggining to index 3 (excluded)
print(arr3[:3])

[1 2 3]


In [56]:
print(arr3[-1:0:-1])

[6 5 4 3 2]


In [57]:
print(arr3[-3:-1])

[4 5]


In [58]:
#using step
print(arr3[1:5:2])

[2 4]


In [59]:
print(arr3[0:-1:2])

[1 3 5]
