# Ian Schlierf
## Week 10 - 10/29/2020
### Python array processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
type(my_list)

list

In [4]:
my_arr = np.array(my_list)

In [5]:
type(my_list)

list

In [6]:
type(my_arr)

numpy.ndarray

In [7]:
print(my_arr.dtype)

int32


In [10]:
fruits = ['Orange', 'Apple', 'Cherry!', 'Potato', 'Grape']

my_strArr = np.array(fruits)

In [11]:
print(my_strArr.dtype)

<U7


In [12]:
my_arr2 = np.array([11,22,33,44,55], dtype = 'S')

In [13]:
print(my_arr2.dtype)

|S2


In [14]:
my_arr2 = np.array([1,2,3,4,5], dtype = 'S')

print(my_arr2.dtype)

|S1


In [15]:
my_arr3 = np.array([5,6,7,8,9], dtype = 'i4')

In [16]:
print(my_arr3.dtype)

int32


In [17]:
ar = np.array(['1','2','3','4','5'], dtype = 'i')

In [18]:
print(ar)

[1 2 3 4 5]


In [19]:
ar = np.array(['a','b','c','d','e'], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [20]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)

In [21]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [22]:
arr = my_arr.astype('i')

In [23]:
print(arr)

[78 88 90 89]


In [24]:
arr = np.array([1,0,0,3,4,5,6,7])

In [25]:
print(arr.dtype)

int32


In [26]:
boolarr = arr.astype(bool)

In [27]:
print(boolarr)

[ True False False  True  True  True  True  True]


In [40]:
lst1 = [1,2,3,4,5,6]
lst2 = [11,22,33,44,55,66]

my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
2


In [41]:
#numpy built-in fucntions to generate arrays from existing arrays
# copy and view, instead of using =


ls = [11,12,13,15]

arr = np.array(ls)
c_arr = arr.copy()

print(arr)
print(c_arr)


[11 12 13 15]
[11 12 13 15]


In [42]:
arr[3] = 4

In [43]:
print(arr)
print(c_arr)


[11 12 13  4]
[11 12 13 15]


In [44]:
#view
ls = [11,12,13,15]

v_arr = np.array(ls)
c_arr = arr.view()

print(arr)
print(c_arr)

[11 12 13  4]
[11 12 13  4]


In [45]:
arr[3]= 4
print(arr)
print(c_arr)

[11 12 13  4]
[11 12 13  4]


In [46]:
v_arr[3]= 4
print(arr)
print(v_arr)

[11 12 13  4]
[11 12 13  4]


In [47]:
print(c_arr.base)
print(v_arr.base)

[11 12 13  4]
None


In [48]:
#shape gives number of elements in each dimension

In [50]:
lst1 = [1,2,3,4,5,6]
lst2 = [11,22,33,44,55,66]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
print(my_arr.shape)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
2
(2, 6)


In [51]:
# shape returns 2 dimensions and each dimesion has 6 elements

In [53]:
arr = np.array(lst1, ndmin=4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5 6]]]]
4
(1, 1, 1, 6)


In [54]:
arr = np.array(lst1, ndmin=6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5 6]]]]]]
6
(1, 1, 1, 1, 1, 6)


In [55]:
#each index in the shape tells the num of elements in that dimension