# Ian Schlierf
## Week 11 - 11/05/2020
### Python numpy universal functions

In [5]:
import numpy as nump


arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [10,11,12,13,14,15,16,17,18,19]

z=[]

for i,j in zip(arr1,arr2):
    z.append(i+j)
    
z

[11, 13, 15, 17, 19, 21, 23, 25, 27]

In [9]:
#zip

fname=("Alice", "Bob", "nardo")
lname = ('Schlierf', 'denardo','Trumpie')

x = zip(fname,lname)
print(tuple(x))

(('Alice', 'Schlierf'), ('Bob', 'denardo'), ('nardo', 'Trumpie'))


In [11]:
ls1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(ls1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [12]:
arr = np.arange(21)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
nump.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [15]:
nump.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
arr = nump.random.randn(10)

In [20]:
arr

array([-0.29641122,  0.92002995, -0.32214524, -0.07558232,  1.67194681,
       -0.05068102, -1.06992472, -0.28362141,  0.20286334,  0.92339781])

In [21]:
arr1 = nump.random.randn(10)

arr1

array([-0.11714216, -0.12969746, -1.00967351, -0.61985485, -0.08165728,
        0.10870273, -0.63204581, -0.28917421,  0.39994473, -0.74872113])

In [22]:
np.add(arr,arr1)

array([-0.41355338,  0.79033249, -1.33181875, -0.69543717,  1.59028953,
        0.05802171, -1.70197053, -0.57279561,  0.60280807,  0.17467668])

In [23]:
nump.maximum(arr,arr1)

array([-0.11714216,  0.92002995, -0.32214524, -0.07558232,  1.67194681,
        0.10870273, -0.63204581, -0.28362141,  0.39994473,  0.92339781])

In [24]:
#nump.where
arr = nump.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [28]:
print(nump.where(arr<4, -1,10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [30]:
nump.where((arr < 4) & (arr >2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [36]:
arr1 = nump.array([1,2,3,4,5])
arr2 = nump.array([10,20,30,40,50])

arr_b = nump.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [34]:
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

In [35]:
arr3

[1, 20, 3, 4, 50]