# Ian Schlierf
## Week 11 - 11/03/2020
### Python numpy creating, processing, transporting arrays

In [6]:
import numpy as np
arr_2d = np.array([[1,2,3,4,5],[5,7,8,9]])

print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d)
print(arr_2d.dtype)

1
(2,)
[list([1, 2, 3, 4, 5]) list([5, 7, 8, 9])]
object


In [2]:
arr_2d = np.array([[1,2,3,4,5],[5,7,8,9]])

In [4]:
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d)
print(arr_2d.dtype)

1
(2,)
[list([1, 2, 3, 4, 5]) list([5, 7, 8, 9])]
object


In [5]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
arr.dtype()

TypeError: 'numpy.dtype' object is not callable

In [8]:
arr.dtype

dtype('float64')

In [9]:
print(arr.ndim)

1


In [10]:
arr_2d = np.zeros((5,5))
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
float64


In [11]:
arr = np.ones((5,5))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [12]:
arr = np.empty((5,5))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [13]:
arr = np.empty((2,2))
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1.50200295e-307 9.96023102e-312]
 [0.00000000e+000 2.44763642e-307]]
2
float64


In [14]:
arr = np.empty((5,5),dtype=int)

print(arr)
print(arr.ndim)
print(arr.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2
int32


In [16]:
#arange
arr = np.arange(10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ar = np.arange(100)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
arr = np.arange(10,100,2)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr)

int32
(45,)
1
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [27]:
#reshape
arr = np.arange(1,13,1)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [28]:
arr2d = arr.reshape(3,4)

print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
#reshape arrays

#1-D to 2-D arrays
arr2d = arr.reshape(4,3)

print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#reshape 1D to 3D
arr3d =arr.reshape(3,2,2)
print(arr3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [31]:
arr3d =arr.reshape(2,3,2)
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
arr3d =arr.reshape(2,2,3)
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
arr2 = arr.reshape(4,4,3)

ValueError: cannot reshape array of size 12 into shape (4,4,3)

In [35]:
#reshape is a view or copy 
print(arr2d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
arr3d =arr.reshape(2,2,-1)
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [38]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [42]:
#Iterating 1D
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [44]:
#iterating a 2D array
arr =np.array([[1,2,3,4],[5,6,7,8]])

for n in arr:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [45]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
for n in arr:
    for x in n:
        print(x)
  

1
2
3
4
5
6
7
8


In [48]:
a3 = np.arange(2,2,3)

In [49]:
a3

array([], dtype=int32)

In [50]:
print(a3)

[]


In [55]:
a3 = np.array([[1,2,3],[4,5,6,7],[8,9,10,11]])
print(a3)

[list([1, 2, 3]) list([4, 5, 6, 7]) list([8, 9, 10, 11])]


In [52]:
print(a3.ndim)

2


In [56]:
#Iterating 3D arrays
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
print(arr3.ndim)

3


In [58]:
for x in arr3:
    for y in x:
        for k in y:
            print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [10 11 12]]


In [61]:
for n in arr3:
    for x in n:
        for n1 in x:
            print(n1)
      

1
2
3
4
5
6
7
8
9
10
11
12


In [62]:
#nditer iterates on each scalar element in the np array
for n in np.nditer(arr3):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [63]:
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
arr_2d[:,::2]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [66]:
arr = np.arange(1,13,1)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [69]:
for idx, n in np.ndenumerate(arr):
    print(idx, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [70]:
arr_2d =np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr_2d.shape)

(4, 2)


In [71]:
for i, n in np.ndenumerate(arr_2d):
    print(i,n)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [72]:
arr_2d*arr_2d

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [73]:
arr_2d**arr_2d

array([[       1,        4],
       [      27,      256],
       [    3125,    46656],
       [  823543, 16777216]], dtype=int32)

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [76]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
arr[::3]

array([ 1,  4,  7, 10])

In [78]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
arr[0:6] =100

In [81]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [82]:
arr.base

In [83]:
print(arr.base)

None
