# Ian Schlierf
## Week 11 - 11/05/2020
### Python numpy universal functions

In [4]:
import numpy as nump


arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [10,11,12,13,14,15,16,17,18,19]

z=[]

for i,j in zip(arr1,arr2):
    z.append(i+j)
    
z

[11, 13, 15, 17, 19, 21, 23, 25, 27]

In [9]:
#zip

fname=("Alice", "Bob", "nardo")
lname = ('Schlierf', 'denardo','Trumpie')

x = zip(fname,lname)
print(tuple(x))

(('Alice', 'Schlierf'), ('Bob', 'denardo'), ('nardo', 'Trumpie'))


In [11]:
ls1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(ls1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [12]:
arr = np.arange(21)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
nump.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [15]:
nump.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
arr = nump.random.randn(10)

In [20]:
arr

array([-0.29641122,  0.92002995, -0.32214524, -0.07558232,  1.67194681,
       -0.05068102, -1.06992472, -0.28362141,  0.20286334,  0.92339781])

In [21]:
arr1 = nump.random.randn(10)

arr1

array([-0.11714216, -0.12969746, -1.00967351, -0.61985485, -0.08165728,
        0.10870273, -0.63204581, -0.28917421,  0.39994473, -0.74872113])

In [22]:
np.add(arr,arr1)

array([-0.41355338,  0.79033249, -1.33181875, -0.69543717,  1.59028953,
        0.05802171, -1.70197053, -0.57279561,  0.60280807,  0.17467668])

In [23]:
nump.maximum(arr,arr1)

array([-0.11714216,  0.92002995, -0.32214524, -0.07558232,  1.67194681,
        0.10870273, -0.63204581, -0.28362141,  0.39994473,  0.92339781])

In [24]:
#nump.where
arr = nump.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [28]:
print(nump.where(arr<4, -1,10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [30]:
nump.where((arr < 4) & (arr >2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [36]:
arr1 = nump.array([1,2,3,4,5])
arr2 = nump.array([10,20,30,40,50])

arr_b = nump.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [34]:
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

In [35]:
arr3

[1, 20, 3, 4, 50]

In [6]:
#Stattistical measures
arr = nump.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)
arr

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.sum()

45

In [8]:
arr.sum(0)

array([12, 15, 18])

In [9]:
arr.sum(1)

array([ 6, 15, 24])

In [10]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [12]:
print(arr)
nump.sum(arr, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [13]:
print(arr)
nump.sum(arr, axis = 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [15]:
print(arr)
nump.sum(arr, axis = None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [16]:
arr.mean()

5.0

In [17]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [18]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [20]:
nump.mean(arr,axis=0)
nump.mean(arr,axis=1)

array([2., 5., 8.])

In [21]:
arr.var()

6.666666666666667

In [22]:
arr.std()

2.581988897471611

In [23]:
arr = nump.array([3,6,8,1,9,10,4,5,47,65,43,23])

arr.sort()

arr

array([ 1,  3,  4,  5,  6,  8,  9, 10, 23, 43, 47, 65])

In [24]:
#Identeitiy array
i = nump.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a = nump.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
a * i


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [27]:
m = nump.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [29]:
#Transpose

arr = nump.array([[1,2,3,4,5],[5,6,7,8]])

print(arr.shape)
print(arr)
print('--------------')

t = arr.T

t

(2,)
[list([1, 2, 3, 4, 5]) list([5, 6, 7, 8])]
--------------


array([list([1, 2, 3, 4, 5]), list([5, 6, 7, 8])], dtype=object)

In [30]:
arr.transpose()

array([list([1, 2, 3, 4, 5]), list([5, 6, 7, 8])], dtype=object)

In [33]:
arr.transpose((0,1))

ValueError: axes don't match array

In [35]:
arr3 = nump.arange(20).reshape((2,5,2))

print(arr3)
print(arr3.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [36]:
arr3.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [37]:
arr3.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [38]:
nump.random.random((4,4))

array([[0.6248942 , 0.70438428, 0.66933672, 0.10897552],
       [0.1728457 , 0.82213883, 0.94796149, 0.26721975],
       [0.90631654, 0.64091559, 0.43311701, 0.52854619],
       [0.33873537, 0.16380861, 0.36479894, 0.09527887]])

In [39]:
from numpy.random import random
random((4,4))

array([[8.73698913e-04, 3.39415458e-01, 1.19717293e-01, 5.40920685e-01],
       [7.32345913e-01, 2.40448272e-01, 6.53726581e-01, 3.20912132e-01],
       [6.44307192e-01, 2.29137715e-01, 3.84536191e-01, 5.07728392e-01],
       [9.06094247e-01, 4.02019920e-01, 6.86651119e-01, 7.03781485e-01]])

In [41]:
from numpy.random import randn

randn(5,5)

array([[ 0.51321393, -1.15306748,  0.2188573 ,  0.50115393,  0.93101949],
       [-0.55967682,  4.00560151, -1.85608019,  2.755571  ,  0.92452268],
       [-0.05670895,  0.36695177, -0.22182534, -0.34878181,  0.02650284],
       [ 0.28505092,  1.61832507, -1.15231593, -0.55757476,  1.13274683],
       [ 0.32941631,  0.30154468,  1.19359465,  1.35584645,  0.95586123]])

In [42]:
nump.random.randint(10,50)

29

In [43]:
website = 'https://numpy.org/doc/stable/reference/'

import webbrowser

webbrowser.open(website)

True

In [44]:
import pandas as pd